### Spring properties
# Service registers under this name
spring:
  application:
    name: ToDoMicroserviceNoteService

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

# HTTP Server (Tomcat) Port
server: 
  port: 8763

    
    