### Spring properties
# Service registers under this name
spring:
  application:
    name: ToDoMicroserviceNoteService
  cloud:
    config:
      uri: localhost:8888
      profile: prod
  profiles:
    active:
    - prod
    
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

# HTTP Server (Tomcat) Port
server: 
  port: 8763
